### ISSUE TITLE
Error reading logs (since 25.05.)

### ISSUE THREAD

**Issue by lordchilli** [gw2scratch/evtc#123]
with logs from 25.05. I get this error message

 ![grafik](https://user-images.githubusercontent.com/85081622/120120591-75c88080-c19e-11eb-80ba-8c33166a0a77.png)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GW2Scratch.EVTCAnalytics.Processing.LogProcessor.GetAgents(ParsedLog log)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GW2Scratch.EVTCAnalytics.Processing.LogProcessor.ProcessLog(ParsedLog log)
   at GW2Scratch.ArcdpsLogManager.Logs.LogData.ParseData(LogAnalytics logAnalytics)

**Comment by Sejsel** [comment]
I am not sure what exactly might be causing that, is there a chance you could share one or two of these logs?

**Comment by lordchilli** [comment]
sure

[20210530-221802.zip](https://github.com/gw2scratch/evtc/files/6566949/20210530-221802.zip)
[20210530-210044.zip](https://github.com/gw2scratch/evtc/files/6566950/20210530-210044.zip)
[20210530-220736.zip](https://github.com/gw2scratch/evtc/files/6566951/20210530-220736.zip)

**Comment by Sejsel** [comment]
The problem can be avoided by updating your arcdps, the May 14 version that was used to record the logs does not quite work properly after the balance patch. It cannot properly read profession data.

I am going to improve handling of this so that everything else, but ultimately, the logs have invalid profession data in them that cannot be fixed, and damage data will be wrong as well.

**Comment by Sejsel** [comment]
These broken logs are [now](ec1c174ccf45cd8ed79e5a0182449017382e423a) handled properly in the Log Manager. If you have someone who plays a core class, it will be shown as unknown, as the data is not available in the log.

Update arcdps to solve the problem of broken logs being generated.

You can get a current build of the log manager [here](https://github.com/gw2scratch/evtc/actions/runs/894264886), it includes the fixes.
