### ISSUE TITLE
Rare crash if the log list is changed during log data updater evaluation

### ISSUE THREAD

**Issue by Sejsel** [gw2scratch/evtc#133]
Happens if new log files are added and picked up by the FileSystemWatcher during LogDataUpdater.GetUpdate().

It should be good enough to make a copy of the log list with `.ToList()` before feeding it the to LogDataUpdater.

```
The background processor for logs has failed critically. Please report the following error:

Exception: System.AggregateException: One or more errors occurred. (Collection was modified; enumeration operation may not execute.)

 ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()

   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()

   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)

   at System.Linq.GroupedEnumerable`2.GetEnumerator()

   at GW2Scratch.ArcdpsLogManager.Logs.Updates.LogDataUpdater.GetUpdates(IEnumerable`1 logs)+MoveNext()

   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)

   at GW2Scratch.ArcdpsLogManager.ManagerForm.<>c__DisplayClass53_0.<ConstructMenuBar>b__2(Object sender, BackgroundProcessorEventArgs args)

   at GW2Scratch.ArcdpsLogManager.Processing.BackgroundProcessor`1.ProcessQueue(CancellationToken cancellationToken)

   --- End of inner exception stack trace ---
```

**Comment by Sejsel** [comment]
This should be fixed in bf41cc5ac02922b550a279763227bb450155411e.

**Comment by Sejsel** [comment]
![image](https://user-images.githubusercontent.com/998408/132020614-862d89e5-e204-49bf-85da-4b2ebc967600.png)

It's not as easy of a fix, there's clearly a race condition. We might need to add some locking when accessing the logs collection

**Comment by Sejsel** [comment]
Reverted the fix for the crash in 98d1f51a4995d189c415ce9fc8f32e1c1196c132 for now, the crash is very rare in comparison to the crashes caused by the fix.
